setup/urls.py
from django.contrib import admin
from django.urls import path
# from todos.views import home, todoListar
from todos.views import todoListarView,todoCriarView

urlpatterns = [
    path("admin/", admin.site.urls),
    # rota que lista as tarefas
    # path("", todoListar),
    path("", todoListarView.as_view(template_name="todos/todolistar.html"),name='todo_listar'),   
    path("criar", todoCriarView.as_view(),name='todo_criar')
]

todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    titulo = models.CharField(max_length=150, null=False, blank=False)
    dtCriacao = models.DateTimeField(auto_now_add=True, null=False, blank=False)
    dtFinalizado = models.DateTimeField(null=True, blank=True) 

todos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Todo
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy


# Create your views here.
def home(request):
    return render(request, "todos/home.html")

'''
def todoListar(request):
    # tarefas = [{
    #     'id':'1',
    #     'Tarefa':'comprar fraldas'
    # }]
    tarefas = Todo.objects.all()
    print(tarefas)
    return render(request, "todos/todolistar.html", {"tarefas": tarefas})
'''

class todoListarView(ListView):
    model = Todo #classe deve usar o modelo ToDo (.\todos\models.py)

class todoCriarView(CreateView):
    model = Todo
    fields = ["titulo","dtFinalizado"]  # Uma lista de campos que o usuario pode alterar
    success_url = reverse_lazy('todo_listar')

todos/templates/todos/home.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>
<body>
    <h1>rota: / </h1>
    <h1>Arquivo: home.html</h1>
    
</body>
</html>

todos/templates/todos/todo_form.html
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <title>Cadastro de Tarefas</title>
  </head>
  <body>
    {% comment %}inicio da barra de navegação{% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">TODO</a>
      </div>
    </nav>
    {% comment %}Fim da barra de navegação{% endcomment %}

    <main class="container">
      <p class="text-start fs-4 fw-bold">Cadastro de tarefas</p>
      <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="ENVIAR" />
      </form>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

todos/templates/todos/todolistar.html
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <title>Listagem de Tarefas</title>
  </head>
  <body>
    {% comment %}inicio da barra de navegação{% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">TODO</a>
      </div>
    </nav>
    {% comment %}Fim da barra de navegação{% endcomment %}

    <main class="container">
      <p class="text-start fs-4 fw-bold">Listagem de tarefas</p>
      
      {% comment %} Inicio botao de criacao de tarefa {% endcomment %}
      <a href="{% url 'todo_criar' %}" 
         type="button" class="btn btn-success">Nova Tarefa</a>
      {% comment %} Fim botao de criacao de tarefa {% endcomment %}

      {% comment %}Inicio da tabela{% endcomment %}
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Titulo</th>
            <th scope="col">Criação</th>
            <th scope="col">Finalizacao</th>
            <th scope="col">Ações</th>
          </tr>
        </thead>
        <tbody>
          {% comment %} {% for tarefa in tarefas %} {% endcomment %}
          {% for tarefa in todo_list %}
            <tr>
              <th scope="row">{{ tarefa.id }}</th>
              <td>{{ tarefa.titulo }}</td>
              <td>{{ tarefa.dtCriacao|date:'SHORT_DATE_FORMAT' }}</td>
              <td>{{ tarefa.dtFinalizacao|date:'SHORT_DATE_FORMAT'|default:'-' }}</td>
              {% comment %}botoes de acoes{% endcomment %}
              <td>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                  <button type="button" class="btn btn-warning">Editar</button>
                  <button type="button" class="btn btn-danger">Excluir</button>
                </div>
              </td>
            
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {% comment %}fim da tabela{% endcomment %}

    </main>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>